using DMS.Models.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Reflection.Metadata;

namespace DMS.Application.Services.Pdf
{
    public class QuotationPdfService
    {
        public byte[] Generate(Sale sale)
        {
            var document = QuestPDF.Fluent.Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Header().Text("QUOTATION").FontSize(20).Bold().AlignCenter();

                    page.Content().PaddingVertical(10).Column(col =>
                    {
                        col.Item().Text($"Date: {DateTime.UtcNow:yyyy-MM-dd}");
                        col.Item().Text($"Quotation ID: SALE-{sale.Id}");
                        col.Item().Text($"Customer: {sale.Customer.FullName}");
                        col.Item().Text($"Product: {sale.Product.Name}");
                        col.Item().Text($"Dealer: {sale.Dealer.Name}");
                        col.Item().Text($"Amount: ₹{sale.QuotationAmount:N0}");
                        col.Item().Text($"Status: {sale.Status}");
                    });

                    page.Footer().AlignCenter().Text("Generated by DMS System");
                });
            });

            return document.GeneratePdf();
        }
    }
}
